spring.application.name=BtgFund
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/BTG}

security.jwt.secret=${JWT_SECRET:U3VwZXJTZWNyZXRLZXlGb3JCdGdGdW5kQXBwMTIzNDU2Nzg5MA==}
security.jwt.expiration-minutes=${JWT_EXP_MINUTES:120}
